BEGIN TRANSACTION;
CREATE TABLE `warning` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`userID`	INTEGER NOT NULL,
	`warningText`	TEXT NOT NULL,
	`warnDate`	TIMESTAMP NOT NULL,
	FOREIGN KEY(`userID`) REFERENCES chatUser(id)
);
CREATE TABLE "chatUser" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`userName` TEXT,
	`tgID` INTEGER NOT NULL,
	`pingAllowed` BOOL NOT NULL DEFAULT 1,
	`activeUser` BOOL NOT NULL DEFAULT 1
);
CREATE TABLE `aliases` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL,
	`userID`	INTEGER NOT NULL,
	`changeDate`	TIMESTAMP NOT NULL
);
COMMIT;
